### ISSUE TITLE
Wrong dependencies installation command in README

### ISSUE THREAD

**Issue by vi** [blinry/gish#11]
> In Debian-based systems, you need to install the following packages:
`cmake libsdl1.2-dev libopenal-dev libvorbis-dev`

Probably meant `sudo apt-get install  libsdl1.2-dev libopenal-dev libvorbis-dev`?

**Comment by blinry** [comment]
Of course! Thanks for reporting! :)

**Comment by RustoMCSpit** [comment]
> Of course! Thanks for reporting! :)

Is this the official Gish release or a fork, I can't find that info anywhere
